# Initially auto-generated by compose2nix from ./docker-compose.yml

inputs: { pkgs, lib, config, ... }:

let
    cfg = config.env.homeServer.services.radicale;
    homeServerUser = config.env.homeServer.user;
    homeServerGroup = config.users.users.${homeServerUser}.group;
    radicaleTag = "3.8.0.0";
in
{
    options.env.homeServer.services.radicale = {

        enable = lib.mkEnableOption "radicale";

        serviceLocation = lib.mkOption {
            type = lib.types.str;
            default = "${config.env.homeServer.servicesLocation}/radicale";
        };

        backup = lib.mkOption {
            type = lib.types.bool;
            default = config.env.homeServer.backup;
        };

    };

    config = lib.mkIf cfg.enable {

        # Runtime
        virtualisation.podman = {
            enable = true;
            autoPrune.enable = true;
            dockerCompat = true;
        };

        # Enable container name DNS for all Podman networks.
        networking.firewall.interfaces = let
            matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
        in {
            "${matchAll}".allowedUDPPorts = [ 53 ];
        };

        virtualisation.oci-containers.backend = "podman";

        # Containers
        virtualisation.oci-containers.containers."radicale" = {
            image = "tomsquest/docker-radicale:${radicaleTag}";
            volumes = [
                "${cfg.serviceLocation}/config:/config:ro"
                "${cfg.serviceLocation}/data:/data:rw"
            ];
            ports = [
                "5232:5232/tcp"
            ];
            log-driver = "journald";
            extraOptions = [
                "--cap-add=CHOWN"
                "--cap-add=KILL"
                "--cap-add=SETGID"
                "--cap-add=SETUID"
                "--cap-drop=ALL"
                "--health-cmd=curl -f http://127.0.0.1:5232 || exit 1"
                "--health-interval=30s"
                "--health-retries=3"
                "--memory=268435456b"
                "--network-alias=radicale"
                "--network=radicale_default"
                "--security-opt=no-new-privileges:true"
            ];
            podman.user = homeServerUser;
        };
        systemd.services."podman-radicale" = {
            serviceConfig = {
                Restart = lib.mkOverride 90 "always";
                User = homeServerUser;
            };
            after = [
                "podman-network-radicale_default.service"
            ];
            requires = [
                "podman-network-radicale_default.service"
            ];
            partOf = [
                "podman-compose-radicale-root.target"
            ];
            wantedBy = [
                "podman-compose-radicale-root.target"
            ];
        };

        # Networks
        systemd.services."podman-network-radicale_default" = {
            path = [ pkgs.podman "/run/wrappers" ];
            serviceConfig = {
                Type = "oneshot";
                RemainAfterExit = true;
                ExecStop = "podman network rm -f radicale_default";
                User = homeServerUser;
            };
            script = ''
                podman network inspect radicale_default || podman network create radicale_default
                '';
            partOf = [ "podman-compose-radicale-root.target" ];
            wantedBy = [ "podman-compose-radicale-root.target" ];
        };

        # Root service
        # When started, this will automatically create all resources and start
        # the containers. When stopped, this will teardown all resources.
        systemd.targets."radicale-root" = {
            unitConfig = {
                Description = "Root target generated by compose2nix.";
            };
            wantedBy = [ "multi-user.target" ];
        };

    };
}
