add_newline = false

format = """
${custom.username}\
${custom.hostname}\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$nix_shell\
$jobs\
$status\
$shell\
$character"""

right_format = """
$time\
$battery\
$git_metrics\
${custom.tmux-pin-pane}\
"""

[custom.tmux-pin-pane]
symbol = " "
shell = "sh"
when = 'tmux-pin-pane test'

[custom.username]
command = "whoami"
style = "bold green"
format = '[$output]($style)@'
shell = "sh"
when = 'test -n "$SSH_CLIENT" && test -n "$SSH_TTY"'

[custom.hostname]
command = "hostname"
style = "bold yellow"
format = '[$output]($style) '
shell = "sh"
when = 'test -n "$SSH_CLIENT" && test -n "$SSH_TTY"'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[git_branch]
format = '[([git:\(](bold blue)$branch(:$remote_branch)[\)](bold blue))]($style) '
symbol = "  " # unused
style = 'bold red'

[git_status]
style = 'bold yellow'

[directory]
read_only = " 󰌾"

[git_commit]
tag_symbol = '  '

[nix_shell]
symbol = " "
format = '[$symbol$state]($style) '

[status]
format = '[$status]($style) '
disabled = true

[time]
format = '[$time]($style) '
disabled = true

[git_metrics]
disabled = true

[shell]
disabled = true

[localip]
disabled = true
