# Initially auto-generated by compose2nix from ./docker-compose.yml

inputs: { pkgs, lib, config, ... }:

let
    cfg = config.env.homeServer.services.navidrome;
    homeServerUser = config.env.homeServer.user;
    homeServerGroup = config.users.users.${homeServerUser}.group;
    navidromeTag = "0.64.1";
in
{
    options.env.homeServer.services.navidrome = {

        enable = lib.mkEnableOption "navidrome";

        serviceLocation = lib.mkOption {
            type = lib.types.str;
            default = "${config.env.homeServer.servicesLocation}/navidrome";
        };

        backup = lib.mkOption {
            type = lib.types.bool;
            default = config.env.homeServer.backup;
        };

    };

    config = lib.mkIf cfg.enable {

        # Runtime
        virtualisation.podman = {
            enable = true;
            autoPrune.enable = true;
            dockerCompat = true;
        };

        # Enable container name DNS for all Podman networks.
        networking.firewall.interfaces = let
            matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
        in {
            "${matchAll}".allowedUDPPorts = [ 53 ];
        };

        virtualisation.oci-containers.backend = "podman";

        # Containers
        virtualisation.oci-containers.containers."navidrome-navidrome" = {
            image = "deluan/navidrome:${navidromeTag}";
            volumes = [
                "${cfg.serviceLocation}/data:/data:rw"
                "${cfg.serviceLocation}/music:/music:ro"
            ];
            ports = [
                "4533:4533/tcp"
            ];
            log-driver = "journald";
            extraOptions = [
                "--userns=keep-id"
                "--network-alias=navidrome"
                "--network=navidrome_default"
            ];
            podman.user = homeServerUser;
        };
        systemd.services."podman-navidrome-navidrome" = {
            serviceConfig = {
                Restart = lib.mkOverride 90 "always";
                User = homeServerUser;
            };
            after = [
                "podman-network-navidrome_default.service"
            ];
            requires = [
                "podman-network-navidrome_default.service"
            ];
            partOf = [
                "podman-compose-navidrome-root.target"
            ];
            wantedBy = [
                "podman-compose-navidrome-root.target"
            ];
        };

        # Networks
        systemd.services."podman-network-navidrome_default" = {
            path = [ pkgs.podman "/run/wrappers" ];
            serviceConfig = {
                Type = "oneshot";
                RemainAfterExit = true;
                ExecStop = "podman network rm -f navidrome_default";
                User = homeServerUser;
            };
            script = ''
                podman network inspect navidrome_default || podman network create navidrome_default
                '';
            partOf = [ "podman-compose-navidrome-root.target" ];
            wantedBy = [ "podman-compose-navidrome-root.target" ];
        };

        # Root service
        # When started, this will automatically create all resources and start
        # the containers. When stopped, this will teardown all resources.
        systemd.targets."navidrome-root" = {
            unitConfig = {
                Description = "Root target generated by compose2nix.";
            };
            wantedBy = [ "multi-user.target" ];
        };

    };
}
